version: '3'
services:
  mongodb:
    image: mongo
    command: mongod
    ports:
      - 27017:27017
  mongo_seed:
    image: mongo
    volumes:
      - ./data.json:/data.json
    links:
      - mongodb
    command: mongoimport --host mongodb --db seconddrivedb --collection cars --type json --file data.json --jsonArray